#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0206, AA0218, AA0228, AL0424, AW0006 // ForNAV settings
dotnet // --> Reports ForNAV Autogenerated code - do not delete or modify
{
    assembly("ForNav.Reports.6.3.0.2259")
    {
        type(ForNav.Report_6_3_0_2259; ForNavReport51516865_v6_3_0_2259) { }
    }
} // Reports ForNAV Autogenerated code - do not delete or modify -->

Report 51516865 "Recover Loan Repayment Unall"
{
    RDLCLayout = './Layouts/RecoverLoanRepaymentUnall.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Loans Register"; "Loans Register")
        {
            RequestFilterFields = "Loan  No.", "Client Code", "Account No", "Repayment Start Date", "Date filter";
            column(ReportForNavId_1000000000; 1000000000) { } // Autogenerated by ForNav - Do not delete
            column(LoanNo_LoansRegister; "Loans Register"."Loan  No.")
            {
            }
            column(ApprovedAmount_LoansRegister; "Loans Register"."Approved Amount")
            {
            }
            column(Interest_LoansRegister; "Loans Register".Interest)
            {
            }
            trigger OnPreDataItem();
            begin
                GeneralJnl.Reset;
                GeneralJnl.SetRange(GeneralJnl."Journal Template Name", 'GENERAL');
                GeneralJnl.SetRange(GeneralJnl."Journal Batch Name", 'RECOVERY');
                if GeneralJnl.Find('-') then
                    GeneralJnl.DeleteAll;
            end;

            trigger OnAfterGetRecord();
            var
                FOSABalance: Decimal;
            begin
                CalcFields("Outstanding Balance", "Interest Due", "Oustanding Interest");
                FOSABalance := 0;
                RepaymentPeriod := WorkDate;
                //RepaymentPeriod:=20170216D;
                //Interest Due
                if RunBal > 0 then begin
                    Loans.Reset;
                    Loans.SetCurrentkey(Loans.Source, Loans."Client Code");
                    Loans.SetRange(Loans."Loan  No.", "Loan  No.");
                    Loans.SetRange(Loans."Client Code", "Client Code");
                    if Loans.Get(Loans."Product Code") then
                        if Loans."Product Code" = 'DIVADV' then begin
                            Message(Format(Loans."Product Code"));
                            //Loans.SETRANGE(Loans."Recovery Mode",Loans."Recovery Mode"::Pension);
                            if Loans.Find('-') then begin
                                Cust.Reset;
                                Cust.SetRange(Cust."BOSA Account No", "Client Code");
                                if Cust.Find('-') then begin
                                    "Account No" := Cust."No.";
                                    Cust.CalcFields(Cust.Balance);
                                    AvailableBal := (Cust.Balance);
                                end;
                                // FOSABalance:=FnGetAvailableBalance("Account No");
                                FOSABalance := AvailableBal;
                                BosaSetUp.Get();
                                RunBal := FOSABalance;
                                if Loans.Get(Loans."Product Code") then
                                    if Loans."Product Code" = 'DIVADV' then begin
                                        Message(Format(Loans."Product Code"));
                                        repeat
                                            Loans.CalcFields(Loans."Outstanding Balance", Loans."Interest Due", Loans."Loans Insurance", Loans."Oustanding Interest", Loans."Penalty Charged");
                                            RunBal := FOSABalance;
                                            RunBal := FOSABalance;
                                            if (Loans."Oustanding Interest" > 0) and (RunBal > 0) then begin
                                                LOustanding := 0;
                                                LineNo := LineNo + 10000;
                                                GeneralJnl.Init;
                                                GeneralJnl."Journal Template Name" := 'GENERAL';
                                                GeneralJnl."Journal Batch Name" := 'RECOVERY';
                                                GeneralJnl."Posting Date" := Today;
                                                GeneralJnl.Description := 'Interest Due';
                                                GeneralJnl."Document No." := "Loan  No.";
                                                GeneralJnl."Line No." := LineNo;
                                                GeneralJnl."Account Type" := GeneralJnl."account type"::Vendor;
                                                GeneralJnl."Account No." := "Account No";
                                                GeneralJnl."Transaction Type" := GeneralJnl."transaction type"::"Interest Paid";
                                                GeneralJnl."Loan No" := Loans."Loan  No.";
                                                if RunBal > Loans."Oustanding Interest" then
                                                    GeneralJnl.Amount := (Loans."Oustanding Interest" * -1)
                                                else
                                                    GeneralJnl.Amount := RunBal * -1;
                                                GeneralJnl."Shortcut Dimension 1 Code" := 'FOSA';
                                                GeneralJnl."Bal. Account Type" := GeneralJnl."bal. account type"::Vendor;
                                                GeneralJnl."Bal. Account No." := "Account No";
                                                //GeneralJnl."Shortcut Dimension 2 Code":=SURESETPFactory.FnGetUserBranch();
                                                GeneralJnl.Insert;
                                            end;
                                            RunBal := RunBal - GeneralJnl.Amount;
                                            Message('RunBal is %1', RunBal);
                                        until Loans.Next = 0;
                                    end;
                            end;
                        end;
                    /*
                    //Loan Repayments
                    MESSAGE('RunBal is %1',RunBal);
                    IF RunBal >0 THEN BEGIN
                    Loans.RESET;
                    Loans.SETCURRENTKEY(Loans.Source,Loans."Client Code");
                    Loans.SETRANGE(Loans."Loan  No.","Loan  No.");
                    Loans.SETRANGE(Loans."Client Code",ObjMember."No.");
                    //Loans.SETRANGE(Loans."Account No","Account No");
                    //Loans.SETRANGE(Loans."Recovery Mode",Loans."Recovery Mode"::Pension);
                    IF Loans.FIND('-') THEN BEGIN
                    REPEAT
                    //Get Last Day of the previous month
                    IF Loans."Repayment Frequency"=Loans."Repayment Frequency"::Monthly THEN BEGIN
                      IF RepaymentPeriod=CALCDATE('CM',RepaymentPeriod) THEN BEGIN
                            LastMonth:=RepaymentPeriod;
                          END ELSE BEGIN
                            LastMonth:=CALCDATE('-1M',RepaymentPeriod);
                          END;
                        LastMonth:=CALCDATE('CM',LastMonth);
                     END;
                    //End Get Last Day of the previous month
                    //Get Scheduled Balance
                      LSchedule.RESET;
                      LSchedule.SETRANGE(LSchedule."Loan No.","Loan  No.");
                      LSchedule.SETRANGE(LSchedule."Repayment Date",LastMonth);
                        IF LSchedule.FINDFIRST THEN BEGIN
                          ScheduledLoanBal:=LSchedule."Loan Amount";
                        END;
                    //End Get Scheduled Balance
                    //Get Loan Bal as per the date filter
                      DateFilter:='..'+FORMAT(LastMonth);*/
                    Loans.Reset;
                    Loans.SetRange(Loans."Loan  No.", "Loan  No.");
                    Loans.SetFilter(Loans."Date filter", DateFilter);
                    if Loans.Find('-') then begin
                        Loans.CalcFields(Loans."Outstanding Balance");
                        LBal := Loans."Outstanding Balance";
                    end;
                    //End Get Loan Bal as per the date filter
                    //Amount in Arrears
                    Arrears := ScheduledLoanBal - LBal;
                    if (Arrears > 0) or (Arrears = 0) then begin
                        Arrears := 0
                    end else
                        Arrears := Arrears;
                    //End Amount in Arrears
                    Loans.CalcFields(Loans."Outstanding Balance", Loans."Interest Due", Loans."Loans Insurance", Loans."Oustanding Interest", Loans."Penalty Charged");
                    if (Loans."Outstanding Balance" > 0) and (RunBal > 0) then begin
                        LineNo := LineNo + 10000;
                        GeneralJnl.Init;
                        GeneralJnl."Journal Template Name" := 'GENERAL';
                        GeneralJnl."Journal Batch Name" := 'RECOVERY';
                        GeneralJnl."Posting Date" := Today;
                        GeneralJnl.Description := 'Principal Repayment';
                        GeneralJnl."Document No." := "Loan  No.";
                        GeneralJnl."Line No." := LineNo;
                        GeneralJnl."Account No." := "Client Code";
                        GeneralJnl."Account Type" := GeneralJnl."account type"::Member;
                        GeneralJnl."Transaction Type" := GeneralJnl."transaction type"::"Loan Repayment";
                        GeneralJnl."Loan No" := Loans."Loan  No.";
                        GeneralJnl.Amount := Loans."Loan Principle Repayment" * -1;
                        if RunBal > (Arrears * -1) then
                            GeneralJnl.Amount := (Arrears)
                        else
                            GeneralJnl.Amount := RunBal * -1;
                        GeneralJnl."Shortcut Dimension 1 Code" := 'BOSA';
                        GeneralJnl."Bal. Account Type" := GeneralJnl."bal. account type"::Vendor;
                        GeneralJnl."Bal. Account No." := "Account No";
                        //GeneralJnl."Shortcut Dimension 2 Code":=SURESETPFactory.FnGetUserBranch();
                        GeneralJnl.Insert;
                        RunBal := RunBal - GeneralJnl.Amount;
                    end;
                    //UNTIL Loans.NEXT = 0;
                end;
                //

            end;

            trigger OnPostDataItem();
            begin
                /*GeneralJnl.RESET;
				GeneralJnl.SETRANGE(GeneralJnl."Journal Template Name",'GENERAL');
				GeneralJnl.SETRANGE(GeneralJnl."Journal Batch Name",'RECOVERY');
				IF GeneralJnl.FIND('-') THEN BEGIN
				CODEUNIT.RUN(CODEUNIT::"Gen. Jnl.-Post Sacco",GeneralJnl);
				END;
				*/

            end;

        }
    }

    requestpage
    {


        SaveValues = false;
        layout
        {
            area(content)
            {
                group(Options)
                {
                    Caption = 'Options';
                    field(ForNavOpenDesigner; ReportForNavOpenDesigner)
                    {
                        ApplicationArea = Basic;
                        Caption = 'Design';
                        Visible = ReportForNavAllowDesign;
                        trigger OnValidate()
                        begin
                            ReportForNav.LaunchDesigner(ReportForNavOpenDesigner);
                            CurrReport.RequestOptionsPage.Close();
                        end;

                    }
                }
            }
        }

        actions
        {
        }
        trigger OnOpenPage()
        begin
            ReportForNavOpenDesigner := false;
        end;
    }

    trigger OnInitReport()
    begin
        ;
        ReportsForNavInit;

    end;

    trigger OnPostReport()
    begin
        ;
        ReportForNav.Post;
    end;

    trigger OnPreReport()
    begin
        ;
        ReportsForNavPre;
    end;

    var
        Loans: Record "Loans Register";
        ReceiptAllocations: Record "Receipt Allocation";
        ObjMember: Record Customer;
        ObjAccTypes: Record "Account Types-Saving Products";
        AvailableBal: Decimal;
        NoSetup: Record "Sacco No. Series";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        InterestDueAmt: Decimal;
        PrincipleRepaymentAmt: Decimal;
        GeneralJnl: Record "Gen. Journal Line";
        BosaSetUp: Record "Sacco General Set-Up";
        RunBal: Decimal;
        Cust: Record Vendor;
        LOustanding: Decimal;
        LineNo: Integer;
        RepaymentPeriod: Date;
        LastMonth: Date;
        LSchedule: Record "Loan Repayment Schedule";
        ScheduledLoanBal: Decimal;
        DateFilter: Text[100];
        LBal: Decimal;
        Arrears: Decimal;
        IntCharged: Decimal;
        PrincipleCharged: Decimal;

    // --> Reports ForNAV Autogenerated code - do not delete or modify
    var
        [WithEvents]
        ReportForNav: DotNet ForNavReport51516865_v6_3_0_2259;
        ReportForNavOpenDesigner: Boolean;
        [InDataSet]
        ReportForNavAllowDesign: Boolean;

    local procedure ReportsForNavInit();
    var
        ApplicationSystemConstants: Codeunit "Application System Constants";
        addInFileName: Text;
        tempAddInFileName: Text;
        path: DotNet Path;
        ReportForNavObject: Variant;
    begin
        addInFileName := ApplicationPath() + 'Add-ins\ReportsForNAV_6_3_0_2259\ForNav.Reports.6.3.0.2259.dll';
        if not File.Exists(addInFileName) then begin
            tempAddInFileName := path.GetTempPath() + '\Microsoft Dynamics NAV\Add-Ins\' + ApplicationSystemConstants.PlatformFileVersion() + '\ForNav.Reports.6.3.0.2259.dll';
            if not File.Exists(tempAddInFileName) then
                Error('Please install the ForNAV DLL version 6.3.0.2259 in your service tier Add-ins folder under the file name "%1"\\If you already have the ForNAV DLL on the server, you should move it to this folder and rename it to match this file name.', addInFileName);
        end;
        ReportForNavObject := ReportForNav.GetLatest(CurrReport.OBJECTID, CurrReport.Language, SerialNumber, UserId, CompanyName);
        ReportForNav := ReportForNavObject;
        ReportForNav.Init();
    end;

    local procedure ReportsForNavPre();
    begin
        ReportForNav.OpenDesigner := ReportForNavOpenDesigner;
        if not ReportForNav.Pre() then CurrReport.Quit();
    end;

    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
